# Generated by Django 4.2.15 on 2024-10-17 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MarathonServer', '0004_station'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marathon',
            old_name='station',
            new_name='station_number',
        ),
    ]
