# Generated by Django 4.2.15 on 2024-10-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarathonServer', '0008_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marathon',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
