# Generated by Django 4.2.15 on 2024-09-19 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marathon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marathon_name', models.CharField(max_length=255, unique=True)),
                ('laps', models.IntegerField()),
                ('race_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Racer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('team_name', models.CharField(blank=True, max_length=255, null=True)),
                ('group', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True)),
                ('marathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racers', to='MarathonServer.marathon')),
            ],
        ),
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_number', models.IntegerField()),
                ('checkpoint_time', models.DateTimeField()),
                ('marathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='MarathonServer.marathon')),
                ('racer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='MarathonServer.racer')),
            ],
        ),
    ]
