# Generated by Django 4.2.15 on 2024-09-19 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MarathonServer', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='racer',
            unique_together={('marathon', 'uid')},
        ),
    ]
