# Generated by Django 4.2.15 on 2024-10-17 11:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MarathonServer', '0002_alter_racer_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marathon',
            old_name='laps',
            new_name='station',
        ),
        migrations.AddField(
            model_name='marathon',
            name='gun_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marathon',
            name='status',
            field=models.CharField(default='upcoming', max_length=50),
        ),
    ]
