# Generated by Django 4.2.15 on 2024-10-17 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MarathonServer', '0003_rename_laps_marathon_station_marathon_gun_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=255)),
                ('marathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='MarathonServer.marathon')),
            ],
        ),
    ]
