# Generated by Django 4.2.15 on 2024-10-17 11:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MarathonServer', '0005_rename_station_marathon_station_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='station_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='station',
            name='station_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
