# Generated by Django 4.2.15 on 2024-10-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarathonServer', '0006_station_station_number_alter_station_station_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='racer',
            old_name='group',
            new_name='age_gender_group',
        ),
        migrations.RemoveField(
            model_name='racer',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='racer',
            name='note',
        ),
        migrations.AddField(
            model_name='racer',
            name='km_group',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
