# Generated by Django 4.2.15 on 2024-10-17 16:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('MarathonServer', '0009_alter_marathon_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marathon',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
